/*
*	ICP Project: BlockEditor
*	Authors: Tomáš Pazdiora (xpazdi02), Michal Pospíšil (xpospi95)
*	File: blockeditor.h
*/

/**
 * @file blockeditor.h
 * @brief UI Class for main window
 * @details Header contains declarations generated by Qt Designer (actual file is generated during compilation)
 *          and some handwritten declarations for other actions
 * @author Tomáš Pazdiora
 * @author Michal Pospíšil
 */

#ifndef BLOCKEDITOR_H
#define BLOCKEDITOR_H

#include <QMainWindow>
#include "graph_ui.h"

QT_BEGIN_NAMESPACE
class QAction;
class QMenu;
QT_END_NAMESPACE

namespace Ui {
class BLOCKEDITOR;
}

class BLOCKEDITOR : public QMainWindow
{
    Q_OBJECT
private:
	GraphUI &graph;
public:
	explicit BLOCKEDITOR(GraphUI &g, QWidget *parent = 0);
	~BLOCKEDITOR();

protected:
    void closeEvent(QCloseEvent *event) Q_DECL_OVERRIDE;

private slots:
    void open();
	void merge();
    bool save();
    bool saveAs();
	void compute();
	void step();
	void reset();
    void help();
    void about();
    void documentWasModified();
	void delBlock();

private:
	Ui::BLOCKEDITOR *ui;

	void deleteActions();
    void createActions();
    void createMenus();
    void createToolBars();
    bool maybeSave();
	void loadFile(const QString &fileName, bool merge);
    bool saveFile(const QString &fileName);
    void setCurrentFile(const QString &fileName);

    QString curFile;

    QMenu *fileMenu;
    QMenu *helpMenu;
    QToolBar *fileToolBar;
    QToolBar *actionToolBar;
    QToolBar *helpToolBar;
    QAction *openAct;
	QAction *mergeAct;
    QAction *saveAct;
    QAction *saveAsAct;
    QAction *exitAct;
    QAction *computeAct;
    QAction *stepAct;
    QAction *resetAct;
	QAction* deleteAct;
    QAction *helpAct;
    QAction *aboutAct;
};

#endif // BLOCKEDITOR_H
