#ifndef BLOCKS_H
#define BLOCKS_H

enum BlockType {
	SCAL_INPUT = 0,
	VECTOR_INPUT = 1,
	MAT2_INPUT = 2,
	SCAL_OUTPUT = 3,
	VECTOR_OUTPUT = 4,
	MAT2_OUTPUT = 5,
	VECTOR_ADD = 10,
	VECTOR_SUB = 11,
	SCALAR_ADD = 12,
	SCALAR_SUB = 13,
	VEC_SCAL_MULTIPLY = 14
};

#endif // BLOCKS_H
